<?php
$groups = $this->helper('customer')->getGroups()->toOptionArray();
$current_group = end($groups);
foreach ($groups as $group) {
    if (Mage::getSingleton('customer/session')->getCustomer()->getGroupId() == $group['value']) {
        $current_group = $group;
        break;
    }
}
?>
<div class="welcome-msg">
    <p class="hello-account"><span class="message"><?php echo $this->__('Hello, %s!', $this->htmlEscape($this->getCustomerName())) ?> 欢迎您回来，您当前的等级是 </span><span class="current-group"><?php echo $current_group['label'] ?></span></p>
</div>

